import {
  BackgroundColorOption,
  BusinessSettings,
  EnhancementSettings,
  OutfitOption,
  PhotoPreset,
} from '../types';

export const PHOTO_PRESETS: PhotoPreset[] = [
  {
    id: 'passport',
    nameBn: 'পাসপোর্ট ছবি (Passport)',
    nameEn: 'Passport Photo',
    widthMm: 40,
    heightMm: 50,
    defaultDpi: 300,
    descriptionBn: 'বাংলাদেশ ও আন্তর্জাতিক পাসপোর্ট স্ট্যান্ডার্ড (৪০মিমি × ৫০মিমি)',
    faceHeightRatio: 0.72,
    topMarginRatio: 0.10,
  },
  {
    id: 'epassport',
    nameBn: 'ই-পাসপোর্ট ছবি (E-Passport)',
    nameEn: 'E-Passport Photo',
    widthMm: 40,
    heightMm: 50,
    defaultDpi: 300,
    descriptionBn: 'বায়োমেট্রিক ই-পাসপোর্ট ফ্রেম ও সুনির্দিষ্ট হেডস্পেস (৪০মিমি × ৫০মিমি)',
    faceHeightRatio: 0.75,
    topMarginRatio: 0.08,
  },
  {
    id: 'visa',
    nameBn: 'ভিসা ছবি (Visa Standard)',
    nameEn: 'Visa Photo',
    widthMm: 35,
    heightMm: 45,
    defaultDpi: 300,
    descriptionBn: 'সেনজেন, যুক্তরাজ্য ও এশীয় দেশসমূহের ভিসা স্ট্যান্ডার্ড (৩৫মিমি × ৪৫মিমি)',
    faceHeightRatio: 0.70,
    topMarginRatio: 0.10,
  },
  {
    id: 'us_visa',
    nameBn: 'ইউএস ভিসা ছবি (US Visa 2x2")',
    nameEn: 'US Visa (2x2 inch)',
    widthMm: 50.8,
    heightMm: 50.8,
    defaultDpi: 300,
    descriptionBn: 'আমেরিকান ভিসা ও ডিভি লটারি (২ ইঞ্চি × ২ ইঞ্চি)',
    faceHeightRatio: 0.65,
    topMarginRatio: 0.12,
  },
  {
    id: 'birth_reg',
    nameBn: 'জন্ম নিবন্ধন ছবি (Birth Registration)',
    nameEn: 'Birth Registration Photo',
    widthMm: 35,
    heightMm: 45,
    defaultDpi: 300,
    descriptionBn: 'সরকারি জন্ম ও মৃত্যু নিবন্ধন সনদ ফরম্যাট (৩৫মিমি × ৪৫মিমি)',
    faceHeightRatio: 0.70,
    topMarginRatio: 0.10,
  },
  {
    id: 'job_app',
    nameBn: 'চাকরির আবেদন ছবি (Job Application)',
    nameEn: 'Job Application Photo',
    widthMm: 40,
    heightMm: 50,
    defaultDpi: 300,
    descriptionBn: 'সরকারি ও বেসরকারি চাকরির আবেদন (৩০০ × ৩০০ পিক্সেল বা ৪০×৫০মিমি)',
    faceHeightRatio: 0.70,
    topMarginRatio: 0.11,
  },
  {
    id: 'cv_photo',
    nameBn: 'সিভি / জীবনবৃত্তান্ত ছবি (CV / Resume)',
    nameEn: 'CV / Resume Photo',
    widthMm: 45,
    heightMm: 55,
    defaultDpi: 300,
    descriptionBn: 'প্রফেশনাল কর্পোরেট ও প্রফেশনাল পোর্টফোলিও (৪৫মিমি × ৫৫মিমি)',
    faceHeightRatio: 0.68,
    topMarginRatio: 0.12,
  },
  {
    id: 'custom',
    nameBn: 'কাস্টম সাইজ (Custom Size)',
    nameEn: 'Custom Size',
    widthMm: 40,
    heightMm: 50,
    defaultDpi: 300,
    descriptionBn: 'নিজের প্রয়োজন অনুযায়ী প্রস্থ, উচ্চতা ও DPI নির্ধারণ করুন',
    faceHeightRatio: 0.70,
    topMarginRatio: 0.10,
  },
];

export const BACKGROUND_COLORS: BackgroundColorOption[] = [
  {
    id: 'white',
    nameBn: 'সাদা (White)',
    nameEn: 'White',
    hex: '#FFFFFF',
  },
  {
    id: 'off_white',
    nameBn: 'অফ হোয়াইট (Off White)',
    nameEn: 'Off White',
    hex: '#F8F8F8',
  },
  {
    id: 'light_blue',
    nameBn: 'হালকা নীল (Light Blue)',
    nameEn: 'Light Blue',
    hex: '#EAF6FF',
  },
  {
    id: 'blue',
    nameBn: 'নীল (Blue)',
    nameEn: 'Blue',
    hex: '#D9EEFF',
  },
  {
    id: 'gray',
    nameBn: 'ধূসর (Gray)',
    nameEn: 'Gray',
    hex: '#E5E5E5',
  },
  {
    id: 'light_gray',
    nameBn: 'হালকা ধূসর (Light Gray)',
    nameEn: 'Light Gray',
    hex: '#F3F4F6',
  },
  {
    id: 'light_green',
    nameBn: 'হালকা সবুজ (Light Green)',
    nameEn: 'Light Green',
    hex: '#EAF7EA',
  },
  {
    id: 'dark_blue',
    nameBn: 'গাঢ় নীল (Royal Blue)',
    nameEn: 'Royal Blue',
    hex: '#2563EB',
  },
];

export const OUTFIT_OPTIONS: OutfitOption[] = [
  {
    id: 'original',
    nameBn: 'মূল পোশাক',
    nameEn: 'Original Outfit',
    descriptionBn: 'ছবিতে বিদ্যমান স্বাভাবিক পোশাক অক্ষুণ্ণ থাকবে',
    iconName: 'User',
  },
  {
    id: 'white_shirt',
    nameBn: 'সাদা শার্ট',
    nameEn: 'White Shirt',
    descriptionBn: 'অফিসিয়াল ও পাসপোর্ট উপযুক্ত ক্লাসিক ফরমাল সাদা শার্ট',
    iconName: 'Shirt',
  },
  {
    id: 'blue_shirt',
    nameBn: 'নীল শার্ট',
    nameEn: 'Blue Shirt',
    descriptionBn: 'মার্জিত আকাশি নীল ফরমাল শার্ট',
    iconName: 'Shirt',
  },
  {
    id: 'navy_shirt',
    nameBn: 'নেভি ব্লু শার্ট',
    nameEn: 'Navy Shirt',
    descriptionBn: 'গাঢ় নেভি ব্লু প্রফেশনাল কলার শার্ট',
    iconName: 'Shirt',
  },
  {
    id: 'formal_suit',
    nameBn: 'ফরমাল স্যুট ও টাই',
    nameEn: 'Formal Suit & Tie',
    descriptionBn: 'এক্সিকিউটিভ ডার্ক স্যুট, টাই ও হোয়াইট কলার',
    iconName: 'Briefcase',
  },
  {
    id: 'blazer',
    nameBn: 'কালো ব্লেজার',
    nameEn: 'Black Blazer',
    descriptionBn: 'স্মার্ট ও মার্জিত ফরমাল ডার্ক ব্লেজার',
    iconName: 'Shield',
  },
  {
    id: 'panjabi',
    nameBn: 'সাদা পাঞ্জাবি',
    nameEn: 'White Panjabi',
    descriptionBn: 'মার্জিত ঐতিহ্যবাহী কলার পাঞ্জাবি',
    iconName: 'Sparkles',
  },
  {
    id: 'hijab',
    nameBn: 'হিজাব',
    nameEn: 'Modest Hijab',
    descriptionBn: 'শালীন মার্জিত অফিসিয়াল হিজাব ও ড্রেস',
    iconName: 'Smile',
  },
];

export const DEFAULT_ENHANCEMENTS: EnhancementSettings = {
  beauty: 'LOW',
  smoothSkin: 'LOW',
  brightness: 'LOW',
  contrast: 'LOW',
  sharpness: 'LOW',
  faceEnhance: 'LOW',
  eyeEnhance: 'OFF',
  teethEnhance: 'OFF',
  hairEnhance: 'OFF',
  beardEnhance: 'OFF',
  noiseReduction: 'LOW',
  skinTone: 'LOW',
  colorCorrection: 'LOW',
};

export const DEFAULT_BUSINESS_SETTINGS: BusinessSettings = {
  businessNameBn: 'স্বপন আইটি একাডেমি',
  businessNameEn: 'SITA AI Photo Studio',
  subtitleBn: 'এআই পাসপোর্ট ও অফিসিয়াল ফটো স্টুডিও',
  subtitleEn: 'AI Passport Photo & Official Photo Studio',
  addressBn: 'শায়েস্তাবাদ বাজার, পুরাতন ইউনিয়ন পরিষদের সামনে, বরিশাল সদর, বরিশাল',
  phone: '01632655030',
  whatsapp: '01553298319',
  footerTextBn: '© স্বপন আইটি একাডেমি - বরিশাল সদর। সর্বস্বত্ব সংরক্ষিত।',
};
